# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'estadisticas.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(1920, 1080)
        window.setMinimumSize(QtCore.QSize(1920, 1080))
        window.setMaximumSize(QtCore.QSize(1920, 1080))
        window.setStyleSheet("QWidget#centralwidget{\n"
"background-color: rgb(102, 111, 152);\n"
"background-color: rgb(45, 50, 80);}")
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.bt_volver = QtWidgets.QPushButton(self.centralwidget)
        self.bt_volver.setGeometry(QtCore.QRect(1480, 730, 300, 100))
        self.bt_volver.setMinimumSize(QtCore.QSize(300, 100))
        self.bt_volver.setMaximumSize(QtCore.QSize(300, 16777215))
        self.bt_volver.setStyleSheet("border-radius:35px;\n"
"font: 75 Bold 20pt \"Montserrat\";\n"
"background-color: rgb(255, 177, 122);\n"
"color: rgb(45, 50, 80);")
        self.bt_volver.setObjectName("bt_volver")
        self.msj_titulo = QtWidgets.QLabel(self.centralwidget)
        self.msj_titulo.setGeometry(QtCore.QRect(390, 40, 1050, 130))
        self.msj_titulo.setMinimumSize(QtCore.QSize(1050, 130))
        self.msj_titulo.setMaximumSize(QtCore.QSize(960, 130))
        self.msj_titulo.setStyleSheet("border:none;\n"
"font: 75 Bold 35pt \"Montserrat\";\n"
"color: rgb(255, 255, 255);")
        self.msj_titulo.setObjectName("msj_titulo")
        self.fr_grafica = QtWidgets.QFrame(self.centralwidget)
        self.fr_grafica.setGeometry(QtCore.QRect(470, 180, 891, 571))
        self.fr_grafica.setStyleSheet("background-color: rgb(45, 50, 80);\n"
"background-color: rgb(102, 111, 152);\n"
"border-radius:20px;")
        self.fr_grafica.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_grafica.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_grafica.setObjectName("fr_grafica")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fr_grafica)
        self.verticalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.qv_imagen = QtWidgets.QVBoxLayout()
        self.qv_imagen.setObjectName("qv_imagen")
        self.verticalLayout_2.addLayout(self.qv_imagen)
        self.verticalLayout_2.setStretch(0, 6)
        window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(window)
        self.statusbar.setObjectName("statusbar")
        window.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(window)
        self.toolBar.setObjectName("toolBar")
        window.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(window)
        self.toolBar_2.setObjectName("toolBar_2")
        window.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "AppComparacionTiempos"))
        self.bt_volver.setText(_translate("window", "Regresar"))
        self.msj_titulo.setText(_translate("window", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">Comparación de tiempos de ejecución</span></p></body></html>"))
        self.toolBar.setWindowTitle(_translate("window", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("window", "toolBar_2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_window()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())
