# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(1920, 1080)
        window.setMinimumSize(QtCore.QSize(1920, 1080))
        window.setMaximumSize(QtCore.QSize(1920, 1080))
        window.setStyleSheet("QWidget#centralwidget{\n"
"background-color: rgb(65, 70, 167);}")
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_izq = QtWidgets.QFrame(self.centralwidget)
        self.frame_izq.setGeometry(QtCore.QRect(0, 0, 960, 1080))
        self.frame_izq.setMinimumSize(QtCore.QSize(960, 1080))
        self.frame_izq.setMaximumSize(QtCore.QSize(960, 1080))
        self.frame_izq.setStyleSheet("border:none;\n"
"background-color: rgb(45, 50, 80);")
        self.frame_izq.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_izq.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_izq.setObjectName("frame_izq")
        self.fr_titulo = QtWidgets.QFrame(self.frame_izq)
        self.fr_titulo.setGeometry(QtCore.QRect(1, 1, 960, 150))
        self.fr_titulo.setMinimumSize(QtCore.QSize(960, 150))
        self.fr_titulo.setMaximumSize(QtCore.QSize(960, 150))
        self.fr_titulo.setStyleSheet("border:none;")
        self.fr_titulo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_titulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_titulo.setObjectName("fr_titulo")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.fr_titulo)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.msj_titulo = QtWidgets.QLabel(self.fr_titulo)
        self.msj_titulo.setMinimumSize(QtCore.QSize(960, 130))
        self.msj_titulo.setMaximumSize(QtCore.QSize(960, 130))
        self.msj_titulo.setStyleSheet("border:none;\n"
"font: 75 Bold 35pt \"Montserrat\";\n"
"color: rgb(255, 255, 255);")
        self.msj_titulo.setObjectName("msj_titulo")
        self.verticalLayout_5.addWidget(self.msj_titulo)
        self.fr_poli = QtWidgets.QFrame(self.frame_izq)
        self.fr_poli.setGeometry(QtCore.QRect(1, 401, 960, 200))
        self.fr_poli.setMinimumSize(QtCore.QSize(960, 200))
        self.fr_poli.setMaximumSize(QtCore.QSize(960, 200))
        self.fr_poli.setStyleSheet("border:none;\n"
"gridline-color: rgb(255, 255, 255);\n"
"selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(255, 255, 255);\n"
"border-top-color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"")
        self.fr_poli.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_poli.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_poli.setObjectName("fr_poli")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.fr_poli)
        self.verticalLayout_7.setContentsMargins(100, 30, 100, 10)
        self.verticalLayout_7.setSpacing(40)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.msj_pol = QtWidgets.QLabel(self.fr_poli)
        self.msj_pol.setMinimumSize(QtCore.QSize(760, 60))
        self.msj_pol.setMaximumSize(QtCore.QSize(760, 60))
        self.msj_pol.setStyleSheet("font: 75 30pt \"Montserrat\";\n"
"color: rgb(255, 255, 255);")
        self.msj_pol.setObjectName("msj_pol")
        self.verticalLayout_7.addWidget(self.msj_pol)
        self.input_user = QtWidgets.QLineEdit(self.fr_poli)
        self.input_user.setMinimumSize(QtCore.QSize(760, 60))
        self.input_user.setMaximumSize(QtCore.QSize(760, 60))
        self.input_user.setStyleSheet("background-color: rgb(66, 71, 111);\n"
"font: 75 Bold 30pt \"Montserrat\";\n"
"border-radius:15px;\n"
"color: rgb(255, 255, 255);")
        self.input_user.setText("")
        self.input_user.setObjectName("input_user")
        self.verticalLayout_7.addWidget(self.input_user)
        self.msj_error = QtWidgets.QLabel(self.fr_poli)
        self.msj_error.setMinimumSize(QtCore.QSize(760, 40))
        self.msj_error.setMaximumSize(QtCore.QSize(760, 40))
        self.msj_error.setStyleSheet("font: 75 30pt \"Montserrat\";\n"
"color: rgb(255, 177, 122);")
        self.msj_error.setText("")
        self.msj_error.setObjectName("msj_error")
        self.verticalLayout_7.addWidget(self.msj_error)
        self.msj_error.raise_()
        self.input_user.raise_()
        self.msj_pol.raise_()
        self.fr_algo = QtWidgets.QFrame(self.frame_izq)
        self.fr_algo.setGeometry(QtCore.QRect(0, 151, 960, 250))
        self.fr_algo.setMinimumSize(QtCore.QSize(960, 250))
        self.fr_algo.setMaximumSize(QtCore.QSize(960, 250))
        self.fr_algo.setStyleSheet("border:none;\n"
"gridline-color: rgb(255, 255, 255);\n"
"selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(255, 255, 255);\n"
"border-top-color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"")
        self.fr_algo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_algo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_algo.setObjectName("fr_algo")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.fr_algo)
        self.verticalLayout_9.setContentsMargins(100, 30, 40, 50)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.msj_algor = QtWidgets.QLabel(self.fr_algo)
        self.msj_algor.setMinimumSize(QtCore.QSize(760, 60))
        self.msj_algor.setMaximumSize(QtCore.QSize(760, 60))
        self.msj_algor.setStyleSheet("font: 75 30pt \"Montserrat\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.msj_algor.setObjectName("msj_algor")
        self.verticalLayout_9.addWidget(self.msj_algor)
        self.comboBox = QtWidgets.QComboBox(self.fr_algo)
        self.comboBox.setMinimumSize(QtCore.QSize(760, 60))
        self.comboBox.setMaximumSize(QtCore.QSize(760, 60))
        self.comboBox.setStyleSheet("font: 75 30pt \"Montserrat\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 71, 111);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_9.addWidget(self.comboBox)
        self.fr_agre = QtWidgets.QFrame(self.frame_izq)
        self.fr_agre.setGeometry(QtCore.QRect(0, 600, 960, 480))
        self.fr_agre.setMinimumSize(QtCore.QSize(960, 480))
        self.fr_agre.setMaximumSize(QtCore.QSize(960, 360))
        self.fr_agre.setStyleSheet("border:none;\n"
"")
        self.fr_agre.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_agre.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_agre.setObjectName("fr_agre")
        self.gridLayout = QtWidgets.QGridLayout(self.fr_agre)
        self.gridLayout.setContentsMargins(30, -1, 30, 60)
        self.gridLayout.setObjectName("gridLayout")
        self.bt_estadis = QtWidgets.QPushButton(self.fr_agre)
        self.bt_estadis.setMinimumSize(QtCore.QSize(300, 100))
        self.bt_estadis.setMaximumSize(QtCore.QSize(300, 16777215))
        self.bt_estadis.setStyleSheet("border-radius:35px;\n"
"background-color: rgb(255, 177, 122);\n"
"font: 75 Bold 20pt \"Montserrat\";\n"
"color: rgb(45, 50, 80);")
        self.bt_estadis.setObjectName("bt_estadis")
        self.gridLayout.addWidget(self.bt_estadis, 1, 1, 1, 1)
        self.bt_eliminar = QtWidgets.QPushButton(self.fr_agre)
        self.bt_eliminar.setMinimumSize(QtCore.QSize(300, 100))
        self.bt_eliminar.setMaximumSize(QtCore.QSize(300, 16777215))
        self.bt_eliminar.setStyleSheet("border-radius:35px;\n"
"background-color: rgb(255, 177, 122);\n"
"font: 75 Bold 20pt \"Montserrat\";\n"
"color: rgb(45, 50, 80);")
        self.bt_eliminar.setObjectName("bt_eliminar")
        self.gridLayout.addWidget(self.bt_eliminar, 1, 0, 1, 1)
        self.bt_agregar = QtWidgets.QPushButton(self.fr_agre)
        self.bt_agregar.setMinimumSize(QtCore.QSize(300, 100))
        self.bt_agregar.setMaximumSize(QtCore.QSize(300, 16777215))
        self.bt_agregar.setStyleSheet("border-radius:35px;\n"
"background-color: rgb(255, 177, 122);\n"
"font: 75 Bold 20pt \"Montserrat\";\n"
"color: rgb(45, 50, 80);")
        self.bt_agregar.setObjectName("bt_agregar")
        self.gridLayout.addWidget(self.bt_agregar, 0, 0, 1, 1)
        self.bt_multiplicar = QtWidgets.QPushButton(self.fr_agre)
        self.bt_multiplicar.setMinimumSize(QtCore.QSize(300, 100))
        self.bt_multiplicar.setMaximumSize(QtCore.QSize(300, 16777215))
        self.bt_multiplicar.setStyleSheet("border-radius:35px;\n"
"font: 75 Bold 20pt \"Montserrat\";\n"
"background-color: rgb(255, 177, 122);\n"
"color: rgb(45, 50, 80);")
        self.bt_multiplicar.setObjectName("bt_multiplicar")
        self.gridLayout.addWidget(self.bt_multiplicar, 0, 1, 1, 1)
        self.frame_der = QtWidgets.QFrame(self.centralwidget)
        self.frame_der.setGeometry(QtCore.QRect(960, 0, 960, 1080))
        self.frame_der.setMinimumSize(QtCore.QSize(960, 1080))
        self.frame_der.setMaximumSize(QtCore.QSize(960, 1080))
        self.frame_der.setStyleSheet("background-color: rgb(102, 111, 152);")
        self.frame_der.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_der.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_der.setObjectName("frame_der")
        self.frame_sup = QtWidgets.QFrame(self.frame_der)
        self.frame_sup.setGeometry(QtCore.QRect(76, 76, 810, 675))
        self.frame_sup.setMinimumSize(QtCore.QSize(810, 675))
        self.frame_sup.setMaximumSize(QtCore.QSize(810, 730))
        self.frame_sup.setStyleSheet("border-radius:40px;\n"
"border-left-color: rgb(245, 194, 17);\n"
"border-color: rgb(245, 194, 17);\n"
"border-right-color: rgb(245, 194, 17);\n"
"background-color: rgb(45, 50, 80);")
        self.frame_sup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_sup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_sup.setObjectName("frame_sup")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_sup)
        self.verticalLayout_3.setContentsMargins(60, 30, 60, 30)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fr_principl = QtWidgets.QFrame(self.frame_sup)
        self.fr_principl.setMinimumSize(QtCore.QSize(690, 615))
        self.fr_principl.setMaximumSize(QtCore.QSize(690, 615))
        self.fr_principl.setStyleSheet("border-color: rgb(245, 194, 17);")
        self.fr_principl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_principl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_principl.setObjectName("fr_principl")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fr_principl)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_pol_0 = QtWidgets.QLabel(self.fr_principl)
        self.lbl_pol_0.setMinimumSize(QtCore.QSize(670, 76))
        self.lbl_pol_0.setMaximumSize(QtCore.QSize(670, 76))
        self.lbl_pol_0.setStyleSheet("font: 75 Bold 30pt \"Montserrat\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lbl_pol_0.setText("")
        self.lbl_pol_0.setObjectName("lbl_pol_0")
        self.verticalLayout_2.addWidget(self.lbl_pol_0)
        self.lbl_pol_1 = QtWidgets.QLabel(self.fr_principl)
        self.lbl_pol_1.setMinimumSize(QtCore.QSize(670, 76))
        self.lbl_pol_1.setMaximumSize(QtCore.QSize(670, 76))
        self.lbl_pol_1.setStyleSheet("font: 75 Bold 30pt \"Montserrat\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lbl_pol_1.setText("")
        self.lbl_pol_1.setObjectName("lbl_pol_1")
        self.verticalLayout_2.addWidget(self.lbl_pol_1)
        self.lbl_pol_2 = QtWidgets.QLabel(self.fr_principl)
        self.lbl_pol_2.setMinimumSize(QtCore.QSize(670, 76))
        self.lbl_pol_2.setMaximumSize(QtCore.QSize(670, 76))
        self.lbl_pol_2.setStyleSheet("font: 75 Bold 30pt \"Montserrat\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lbl_pol_2.setObjectName("lbl_pol_2")
        self.verticalLayout_2.addWidget(self.lbl_pol_2)
        self.lbl_pol_3 = QtWidgets.QLabel(self.fr_principl)
        self.lbl_pol_3.setMinimumSize(QtCore.QSize(670, 76))
        self.lbl_pol_3.setMaximumSize(QtCore.QSize(670, 76))
        self.lbl_pol_3.setStyleSheet("font: 75 Bold 30pt \"Montserrat\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lbl_pol_3.setObjectName("lbl_pol_3")
        self.verticalLayout_2.addWidget(self.lbl_pol_3)
        self.lbl_pol_4 = QtWidgets.QLabel(self.fr_principl)
        self.lbl_pol_4.setMinimumSize(QtCore.QSize(670, 76))
        self.lbl_pol_4.setMaximumSize(QtCore.QSize(670, 76))
        self.lbl_pol_4.setStyleSheet("font: 75 Bold 30pt \"Montserrat\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lbl_pol_4.setObjectName("lbl_pol_4")
        self.verticalLayout_2.addWidget(self.lbl_pol_4)
        self.lbl_pol_5 = QtWidgets.QLabel(self.fr_principl)
        self.lbl_pol_5.setMinimumSize(QtCore.QSize(670, 76))
        self.lbl_pol_5.setMaximumSize(QtCore.QSize(670, 76))
        self.lbl_pol_5.setStyleSheet("font: 75 Bold 30pt \"Montserrat\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lbl_pol_5.setObjectName("lbl_pol_5")
        self.verticalLayout_2.addWidget(self.lbl_pol_5)
        self.lbl_pol_6 = QtWidgets.QLabel(self.fr_principl)
        self.lbl_pol_6.setMinimumSize(QtCore.QSize(670, 76))
        self.lbl_pol_6.setMaximumSize(QtCore.QSize(670, 76))
        self.lbl_pol_6.setStyleSheet("font: 75 Bold 30pt \"Montserrat\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lbl_pol_6.setObjectName("lbl_pol_6")
        self.verticalLayout_2.addWidget(self.lbl_pol_6)
        self.lbl_pol_7 = QtWidgets.QLabel(self.fr_principl)
        self.lbl_pol_7.setMinimumSize(QtCore.QSize(670, 76))
        self.lbl_pol_7.setMaximumSize(QtCore.QSize(670, 76))
        self.lbl_pol_7.setStyleSheet("font: 75 Bold 30pt \"Montserrat\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lbl_pol_7.setObjectName("lbl_pol_7")
        self.verticalLayout_2.addWidget(self.lbl_pol_7)
        self.verticalLayout_3.addWidget(self.fr_principl)
        self.frame_inf = QtWidgets.QFrame(self.frame_der)
        self.frame_inf.setGeometry(QtCore.QRect(76, 804, 810, 200))
        self.frame_inf.setMinimumSize(QtCore.QSize(810, 200))
        self.frame_inf.setMaximumSize(QtCore.QSize(810, 200))
        self.frame_inf.setStyleSheet("border-radius:40px;\n"
"background-color: rgb(45, 50, 80);")
        self.frame_inf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inf.setObjectName("frame_inf")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_inf)
        self.verticalLayout_8.setContentsMargins(30, 10, 30, 10)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.show_resul = QtWidgets.QLabel(self.frame_inf)
        self.show_resul.setMinimumSize(QtCore.QSize(0, 30))
        self.show_resul.setMaximumSize(QtCore.QSize(400, 40))
        self.show_resul.setStyleSheet("font: 75 25pt \"DejaVu Sans\";\n"
"color: rgb(255, 255, 255);")
        self.show_resul.setObjectName("show_resul")
        self.verticalLayout_8.addWidget(self.show_resul)
        self.msj_resul = QtWidgets.QLabel(self.frame_inf)
        self.msj_resul.setMinimumSize(QtCore.QSize(760, 70))
        self.msj_resul.setMaximumSize(QtCore.QSize(760, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.msj_resul.setFont(font)
        self.msj_resul.setStyleSheet("background-color: rgb(254, 254, 254);\n"
"font: 75 Bold 30pt \"Montserrat\";\n"
"border-radius:20px;\n"
"color: rgb(45, 50, 80);")
        self.msj_resul.setText("")
        self.msj_resul.setObjectName("msj_resul")
        self.verticalLayout_8.addWidget(self.msj_resul)
        self.msj_tiempo = QtWidgets.QLabel(self.frame_inf)
        self.msj_tiempo.setMinimumSize(QtCore.QSize(760, 40))
        self.msj_tiempo.setMaximumSize(QtCore.QSize(760, 40))
        self.msj_tiempo.setStyleSheet("font: 75 20pt \"Montserrat\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.msj_tiempo.setObjectName("msj_tiempo")
        self.verticalLayout_8.addWidget(self.msj_tiempo)
        self.bt_limpiar = QtWidgets.QPushButton(self.frame_der)
        self.bt_limpiar.setGeometry(QtCore.QRect(650, 10, 200, 60))
        self.bt_limpiar.setMinimumSize(QtCore.QSize(100, 60))
        self.bt_limpiar.setMaximumSize(QtCore.QSize(200, 60))
        self.bt_limpiar.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 177, 122);\n"
"color: rgb(45, 50, 80);\n"
"font: 75 Bold 20pt \"Montserrat\";\n"
"")
        self.bt_limpiar.setObjectName("bt_limpiar")
        window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(window)
        self.statusbar.setObjectName("statusbar")
        window.setStatusBar(self.statusbar)

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "AppMulPolinomios"))
        self.msj_titulo.setText(_translate("window", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">Multiplicación de polinomios</span></p></body></html>"))
        self.msj_pol.setText(_translate("window", "<html><head/><body><p>Ingrese un polinomio:</p></body></html>"))
        self.msj_algor.setText(_translate("window", "Elija un algoritmo"))
        self.comboBox.setItemText(0, _translate("window", "Lagrange"))
        self.comboBox.setItemText(1, _translate("window", "Vandermonde en R"))
        self.comboBox.setItemText(2, _translate("window", "Vandermonde en I"))
        self.comboBox.setItemText(3, _translate("window", "Bit reverso"))
        self.bt_estadis.setText(_translate("window", "Estadísticas"))
        self.bt_eliminar.setText(_translate("window", "Eliminar"))
        self.bt_agregar.setText(_translate("window", "Agregar"))
        self.bt_multiplicar.setText(_translate("window", "Multiplicar"))
        self.lbl_pol_2.setText(_translate("window", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\"><br/></span></p></body></html>"))
        self.lbl_pol_3.setText(_translate("window", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.lbl_pol_4.setText(_translate("window", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.lbl_pol_5.setText(_translate("window", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.lbl_pol_6.setText(_translate("window", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.lbl_pol_7.setText(_translate("window", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.show_resul.setText(_translate("window", "<html><head/><body><p><span style=\" font-weight:600;\">RESULTADO</span></p></body></html>"))
        self.msj_tiempo.setText(_translate("window", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.bt_limpiar.setText(_translate("window", "Limpiar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_window()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())
